name: Linux

on:
  pull_request:
  push:
  release:
    types: published

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build_type: [ Debug, Release ]
    runs-on: [ubuntu-latest]
    container:
      image: fedora:32
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: dnf install -yq cmake ninja-build gcc-c++ clang-tools-extra python3-PyYAML boost-devel

    - name: Build with GCC
      run: |
        cmake -B build -GNinja -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DP2T_BUILD_TESTS=ON
        cmake --build build --verbose

    - name: Build with Clang
      run: |
        CXX=clang++ cmake -B build-clang -GNinja -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_EXPORT_COMPILE_COMMANDS=1
        cmake --build build-clang --verbose

    - name: Lint with clang-tidy
      run: python3 /usr/share/clang/run-clang-tidy.py -header-filter=poly2tri -p=build-clang

    - name: Unit tests
      run: cd build && ctest --output-on-failure
